set_property IOSTANDARD LVCMOS33 [get_ports clk100]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports outMusic]
set_property PACKAGE_PIN W5 [get_ports clk100]
set_property PACKAGE_PIN A15 [get_ports outMusic]
set_property PACKAGE_PIN U18 [get_ports reset]
